### ISSUE TITLE
DSD+ 2.29 removes -dr and -dh

### ISSUE THREAD

**Issue by GTR8000** [dreinhold/dsdtune#15]
From the release notes of DSD+ 2.29 (released Dec 23rd, 2016):

> **The -dr and -dh command line options have been removed**

Causes dsdtune to throw **'Could not get decode string'** error

Thanks!

**Comment by dreinhold** [comment]
Thanks for the info. I will take a look.

**Comment by DonRichie** [comment]
I feel like having the same problem :(

```
C:\sdrsharp-x86>dsdtune.exe -i SDRSharp_20170227_181124Z_425424992Hz_IQ.wav
Checking option -dr
Running dsd.exe -o0 -O NUL -drXXX ? SDRSharp_20170227_181124Z_425424992Hz_IQ.wav
Could not get decode string
```

**Comment by dreinhold** [comment]
Oh yeah I blew it never looked into this one.
Which version of dsdplus are you running?

**Comment by DonRichie** [comment]
The most recent one: "1.101"
and also the most recent build you provided of dsdtune: "0.1.1"

**Comment by GTR8000** [comment]
Hi Dylan,

The latest public release is 1.101, but it's quite old at this point (Dec 2015). DSDTune works fine as-is with this version.

The issue lies with the Fast Lane releases (currently 2.39), in which the -dr and -dh command line options have been removed.

I assume that you're familiar with Fast Lane, as it's quite popular, especially given how long it's been since they've issued an updated public release.

**Comment by dreinhold** [comment]
Give Release 0.1.2 a try
https://github.com/dreinhold/dsdtune/releases/tag/v0.1.2

Dylan

**Comment by GTR8000** [comment]
It gets through -ds, but bombs on -dd

This is with Fast Lane 2.39, the most current release

I wonder if they've already removed -dd and didn't documents it properly, and of course since it won't get past -dd, I also have no idea about -dv

A shame that they haven't offered more comprehensive documentation as to what was removed, and why

**Comment by dreinhold** [comment]
You can try it from the command line.
dsdplus -o0 -O NUL -ds55 -dv1 ? WAV_FILE_NAME.wav

**Comment by GTR8000** [comment]
I should've remembered that, thanks

-ds and -dv are both still valid; -dd was also removed

**Comment by dreinhold** [comment]
Cool, thanks for checking that.

Give https://github.com/dreinhold/dsdtune/releases/tag/v0.1.3 a try.

Dylan

**Comment by GTR8000** [comment]
That worked, thanks!

**Comment by dreinhold** [comment]
Cool, thanks for testing.
